# layer 1
# num_classes = 5
# layer: Phylum
categories_l1 = [
    {'id': 1, 'name': 'Chordata', 'freebase_id': 'tbd'},
    {'id': 2, 'name': 'Cnidaria', 'freebase_id': 'tbd'},
    {'id': 3, 'name': 'Arthropoda', 'freebase_id': 'tbd'},
    {'id': 4, 'name': 'Echinodermata', 'freebase_id': 'tbd'},
    {'id': 5, 'name': 'Mollusca', 'freebase_id': 'tbd'},
]

# layer 2
# num_classes = 18
# layer: class
categories_l2 = [
    {'id': 1, 'name': 'Actinopterygii', 'freebase_id': 'tbd'},
    {'id': 2, 'name': 'Amphibia', 'freebase_id': 'tbd'},
    {'id': 3, 'name': 'Anthozoa', 'freebase_id': 'tbd'},
    {'id': 4, 'name': 'Malacostraca', 'freebase_id': 'tbd'},
    {'id': 5, 'name': 'Echinoidea', 'freebase_id': 'tbd'},
    {'id': 6, 'name': 'Asteroidea', 'freebase_id': 'tbd'},
    {'id': 7, 'name': 'Diplopoda', 'freebase_id': 'tbd'},
    {'id': 8, 'name': 'Merostomata', 'freebase_id': 'tbd'},
    {'id': 9, 'name': 'Hydrozoa', 'freebase_id': 'tbd'},
    {'id': 10, 'name': 'Chilopoda', 'freebase_id': 'tbd'},
    {'id': 11, 'name': 'Arachnida', 'freebase_id': 'tbd'},
    {'id': 12, 'name': 'Aves', 'freebase_id': 'tbd'},
    {'id': 13, 'name': 'Insecta', 'freebase_id': 'tbd'},
    {'id': 14, 'name': 'Mammalia', 'freebase_id': 'tbd'},
    {'id': 15, 'name': 'Gastropoda', 'freebase_id': 'tbd'},
    {'id': 16, 'name': 'Bivalvia', 'freebase_id': 'tbd'},
    {'id': 17, 'name': 'Polyplacophora', 'freebase_id': 'tbd'},
    {'id': 18, 'name': 'Reptilia', 'freebase_id': 'tbd'},
]

# layer 3
# num_classes = 61
# layer: Order
categories_l3 = [
    {'id': 1, 'name': 'Cypriniformes', 'freebase_id': 'tbd'},
    {'id': 2, 'name': 'Perciformes', 'freebase_id': 'tbd'},
    {'id': 3, 'name': 'Salmoniformes', 'freebase_id': 'tbd'},
    {'id': 4, 'name': 'Anura', 'freebase_id': 'tbd'},
    {'id': 5, 'name': 'Caudata', 'freebase_id': 'tbd'},
    {'id': 6, 'name': 'Actiniaria', 'freebase_id': 'tbd'},
    {'id': 7, 'name': 'Isopoda', 'freebase_id': 'tbd'},
    {'id': 8, 'name': 'Decapoda', 'freebase_id': 'tbd'},
    {'id': 9, 'name': 'Clypeasteroida', 'freebase_id': 'tbd'},
    {'id': 10, 'name': 'Valvatida', 'freebase_id': 'tbd'},
    {'id': 11, 'name': 'Polydesmida', 'freebase_id': 'tbd'},
    {'id': 12, 'name': 'Xiphosurida', 'freebase_id': 'tbd'},
    {'id': 13, 'name': 'Siphonophorae', 'freebase_id': 'tbd'},
    {'id': 14, 'name': 'Forcipulatida', 'freebase_id': 'tbd'},
    {'id': 15, 'name': 'Scolopendromorpha', 'freebase_id': 'tbd'},
    {'id': 16, 'name': 'Camarodonta', 'freebase_id': 'tbd'},
    {'id': 17, 'name': 'Anthoathecata', 'freebase_id': 'tbd'},
    {'id': 18, 'name': 'Araneae', 'freebase_id': 'tbd'},
    {'id': 19, 'name': 'Scorpiones', 'freebase_id': 'tbd'},
    {'id': 20, 'name': 'Ixodida', 'freebase_id': 'tbd'},
    {'id': 21, 'name': 'Passeriformes', 'freebase_id': 'tbd'},
    {'id': 22, 'name': 'Charadriiformes', 'freebase_id': 'tbd'},
    {'id': 23, 'name': 'Podicipediformes', 'freebase_id': 'tbd'},
    {'id': 24, 'name': 'Anseriformes', 'freebase_id': 'tbd'},
    {'id': 25, 'name': 'Coraciiformes', 'freebase_id': 'tbd'},
    {'id': 26, 'name': 'Caprimulgiformes', 'freebase_id': 'tbd'},
    {'id': 27, 'name': 'Suliformes', 'freebase_id': 'tbd'},
    {'id': 28, 'name': 'Gruiformes', 'freebase_id': 'tbd'},
    {'id': 29, 'name': 'Accipitriformes', 'freebase_id': 'tbd'},
    {'id': 30, 'name': 'Pelecaniformes', 'freebase_id': 'tbd'},
    {'id': 31, 'name': 'Procellariiformes', 'freebase_id': 'tbd'},
    {'id': 32, 'name': 'Strigiformes', 'freebase_id': 'tbd'},
    {'id': 33, 'name': 'Galliformes', 'freebase_id': 'tbd'},
    {'id': 34, 'name': 'Piciformes', 'freebase_id': 'tbd'},
    {'id': 35, 'name': 'Falconiformes', 'freebase_id': 'tbd'},
    {'id': 36, 'name': 'Cathartiformes', 'freebase_id': 'tbd'},
    {'id': 37, 'name': 'Lepidoptera', 'freebase_id': 'tbd'},
    {'id': 38, 'name': 'Hemiptera', 'freebase_id': 'tbd'},
    {'id': 39, 'name': 'Hymenoptera', 'freebase_id': 'tbd'},
    {'id': 40, 'name': 'Diptera', 'freebase_id': 'tbd'},
    {'id': 41, 'name': 'Odonata', 'freebase_id': 'tbd'},
    {'id': 42, 'name': 'Coleoptera', 'freebase_id': 'tbd'},
    {'id': 43, 'name': 'Megaloptera', 'freebase_id': 'tbd'},
    {'id': 44, 'name': 'Rodentia', 'freebase_id': 'tbd'},
    {'id': 45, 'name': 'Artiodactyla', 'freebase_id': 'tbd'},
    {'id': 46, 'name': 'Carnivora', 'freebase_id': 'tbd'},
    {'id': 47, 'name': 'Cingulata', 'freebase_id': 'tbd'},
    {'id': 48, 'name': 'Didelphimorphia', 'freebase_id': 'tbd'},
    {'id': 49, 'name': 'Eulipotyphla', 'freebase_id': 'tbd'},
    {'id': 50, 'name': 'Lagomorpha', 'freebase_id': 'tbd'},
    {'id': 51, 'name': 'Proboscidea', 'freebase_id': 'tbd'},
    {'id': 52, 'name': 'Nudibranchia', 'freebase_id': 'tbd'},
    {'id': 53, 'name': 'Aplysiida', 'freebase_id': 'tbd'},
    {'id': 54, 'name': 'Stylommatophora', 'freebase_id': 'tbd'},
    {'id': 55, 'name': 'Trochida', 'freebase_id': 'tbd'},
    {'id': 56, 'name': 'Venerida', 'freebase_id': 'tbd'},
    {'id': 57, 'name': 'Chitonida', 'freebase_id': 'tbd'},
    {'id': 58, 'name': 'Testudines', 'freebase_id': 'tbd'},
    {'id': 59, 'name': 'Crocodylia', 'freebase_id': 'tbd'},
    {'id': 60, 'name': 'Squamata', 'freebase_id': 'tbd'},
    {'id': 61, 'name': 'Rhynchocephalia', 'freebase_id': 'tbd'}
]


# layer 4
# num_classes = 184
# layer: Family
categories_l4 = [
    {'id': 1, 'name': 'Cyprinidae', 'freebase_id': 'tbd'},
    {'id': 2, 'name': 'Centrarchidae', 'freebase_id': 'tbd'},
    {'id': 3, 'name': 'Salmonidae', 'freebase_id': 'tbd'},
    {'id': 4, 'name': 'Zanclidae', 'freebase_id': 'tbd'},
    {'id': 5, 'name': 'Hylidae', 'freebase_id': 'tbd'},
    {'id': 6, 'name': 'Ambystomatidae', 'freebase_id': 'tbd'},
    {'id': 7, 'name': 'Bufonidae', 'freebase_id': 'tbd'},
    {'id': 8, 'name': 'Plethodontidae', 'freebase_id': 'tbd'},
    {'id': 9, 'name': 'Eleutherodactylidae', 'freebase_id': 'tbd'},
    {'id': 10, 'name': 'Microhylidae', 'freebase_id': 'tbd'},
    {'id': 11, 'name': 'Ranidae', 'freebase_id': 'tbd'},
    {'id': 12, 'name': 'Salamandridae', 'freebase_id': 'tbd'},
    {'id': 13, 'name': 'Dendrobatidae', 'freebase_id': 'tbd'},
    {'id': 14, 'name': 'Scaphiopodidae', 'freebase_id': 'tbd'},
    {'id': 15, 'name': 'Actiniidae', 'freebase_id': 'tbd'},
    {'id': 16, 'name': 'Armadillidiidae', 'freebase_id': 'tbd'},
    {'id': 17, 'name': 'Portunidae', 'freebase_id': 'tbd'},
    {'id': 18, 'name': 'Cancridae', 'freebase_id': 'tbd'},
    {'id': 19, 'name': 'Dendrasteridae', 'freebase_id': 'tbd'},
    {'id': 20, 'name': 'Asteropseidae', 'freebase_id': 'tbd'},
    {'id': 21, 'name': 'Hippidae', 'freebase_id': 'tbd'},
    {'id': 22, 'name': 'Xystodesmidae', 'freebase_id': 'tbd'},
    {'id': 23, 'name': 'Varunidae', 'freebase_id': 'tbd'},
    {'id': 24, 'name': 'Limulidae', 'freebase_id': 'tbd'},
    {'id': 25, 'name': 'Grapsidae', 'freebase_id': 'tbd'},
    {'id': 26, 'name': 'Asterinidae', 'freebase_id': 'tbd'},
    {'id': 27, 'name': 'Physaliidae', 'freebase_id': 'tbd'},
    {'id': 28, 'name': 'Asteriidae', 'freebase_id': 'tbd'},
    {'id': 29, 'name': 'Cambaridae', 'freebase_id': 'tbd'},
    {'id': 30, 'name': 'Epialtidae', 'freebase_id': 'tbd'},
    {'id': 31, 'name': 'Scolopendridae', 'freebase_id': 'tbd'},
    {'id': 32, 'name': 'Strongylocentrotidae', 'freebase_id': 'tbd'},
    {'id': 33, 'name': 'Porpitidae', 'freebase_id': 'tbd'},
    {'id': 34, 'name': 'Theraphosidae', 'freebase_id': 'tbd'},
    {'id': 35, 'name': 'Araneidae', 'freebase_id': 'tbd'},
    {'id': 36, 'name': 'Buthidae', 'freebase_id': 'tbd'},
    {'id': 37, 'name': 'Ixodidae', 'freebase_id': 'tbd'},
    {'id': 38, 'name': 'Pisauridae', 'freebase_id': 'tbd'},
    {'id': 39, 'name': 'Dysderidae', 'freebase_id': 'tbd'},
    {'id': 40, 'name': 'Theridiidae', 'freebase_id': 'tbd'},
    {'id': 41, 'name': 'Thomisidae', 'freebase_id': 'tbd'},
    {'id': 42, 'name': 'Salticidae', 'freebase_id': 'tbd'},
    {'id': 43, 'name': 'Oxyopidae', 'freebase_id': 'tbd'},
    {'id': 44, 'name': 'Vaejovidae', 'freebase_id': 'tbd'},
    {'id': 45, 'name': 'Sturnidae', 'freebase_id': 'tbd'},
    {'id': 46, 'name': 'Scolopacidae', 'freebase_id': 'tbd'},
    {'id': 47, 'name': 'Podicipedidae', 'freebase_id': 'tbd'},
    {'id': 48, 'name': 'Aegithalidae', 'freebase_id': 'tbd'},
    {'id': 49, 'name': 'Icteridae', 'freebase_id': 'tbd'},
    {'id': 50, 'name': 'Passerellidae', 'freebase_id': 'tbd'},
    {'id': 51, 'name': 'Anatidae', 'freebase_id': 'tbd'},
    {'id': 52, 'name': 'Alaudidae', 'freebase_id': 'tbd'},
    {'id': 53, 'name': 'Alcedinidae', 'freebase_id': 'tbd'},
    {'id': 54, 'name': 'Trochilidae', 'freebase_id': 'tbd'},
    {'id': 55, 'name': 'Anhingidae', 'freebase_id': 'tbd'},
    {'id': 56, 'name': 'Meliphagidae', 'freebase_id': 'tbd'},
    {'id': 57, 'name': 'Motacillidae', 'freebase_id': 'tbd'},
    {'id': 58, 'name': 'Gruidae', 'freebase_id': 'tbd'},
    {'id': 59, 'name': 'Corvidae', 'freebase_id': 'tbd'},
    {'id': 60, 'name': 'Accipitridae', 'freebase_id': 'tbd'},
    {'id': 61, 'name': 'Aramidae', 'freebase_id': 'tbd'},
    {'id': 62, 'name': 'Ardeidae', 'freebase_id': 'tbd'},
    {'id': 63, 'name': 'Procellariidae', 'freebase_id': 'tbd'},
    {'id': 64, 'name': 'Strigidae', 'freebase_id': 'tbd'},
    {'id': 65, 'name': 'Remizidae', 'freebase_id': 'tbd'},
    {'id': 66, 'name': 'Paridae', 'freebase_id': 'tbd'},
    {'id': 67, 'name': 'Parulidae', 'freebase_id': 'tbd'},
    {'id': 68, 'name': 'Bombycillidae', 'freebase_id': 'tbd'},
    {'id': 69, 'name': 'Phasianidae', 'freebase_id': 'tbd'},
    {'id': 70, 'name': 'Odontophoridae', 'freebase_id': 'tbd'},
    {'id': 71, 'name': 'Picidae', 'freebase_id': 'tbd'},
    {'id': 72, 'name': 'Troglodytidae', 'freebase_id': 'tbd'},
    {'id': 73, 'name': 'Falconidae', 'freebase_id': 'tbd'},
    {'id': 74, 'name': 'Cardinalidae', 'freebase_id': 'tbd'},
    {'id': 75, 'name': 'Fringillidae', 'freebase_id': 'tbd'},
    {'id': 76, 'name': 'Cathartidae', 'freebase_id': 'tbd'},
    {'id': 77, 'name': 'Turdidae', 'freebase_id': 'tbd'},
    {'id': 78, 'name': 'Alcidae', 'freebase_id': 'tbd'},
    {'id': 79, 'name': 'Certhiidae', 'freebase_id': 'tbd'},
    {'id': 80, 'name': 'Sylviidae', 'freebase_id': 'tbd'},
    {'id': 81, 'name': 'Charadriidae', 'freebase_id': 'tbd'},
    {'id': 82, 'name': 'Papilionidae', 'freebase_id': 'tbd'},
    {'id': 83, 'name': 'Rhopalidae', 'freebase_id': 'tbd'},
    {'id': 84, 'name': 'Nymphalidae', 'freebase_id': 'tbd'},
    {'id': 85, 'name': 'Apidae', 'freebase_id': 'tbd'},
    {'id': 86, 'name': 'Bombyliidae', 'freebase_id': 'tbd'},
    {'id': 87, 'name': 'Libellulidae', 'freebase_id': 'tbd'},
    {'id': 88, 'name': 'Lycaenidae', 'freebase_id': 'tbd'},
    {'id': 89, 'name': 'Erebidae', 'freebase_id': 'tbd'},
    {'id': 90, 'name': 'Riodinidae', 'freebase_id': 'tbd'},
    {'id': 91, 'name': 'Lycidae', 'freebase_id': 'tbd'},
    {'id': 92, 'name': 'Calopterygidae', 'freebase_id': 'tbd'},
    {'id': 93, 'name': 'Carabidae', 'freebase_id': 'tbd'},
    {'id': 94, 'name': 'Hesperiidae', 'freebase_id': 'tbd'},
    {'id': 95, 'name': 'Geometridae', 'freebase_id': 'tbd'},
    {'id': 96, 'name': 'Sphingidae', 'freebase_id': 'tbd'},
    {'id': 97, 'name': 'Cantharidae', 'freebase_id': 'tbd'},
    {'id': 98, 'name': 'Pentatomidae', 'freebase_id': 'tbd'},
    {'id': 99, 'name': 'Chrysomelidae', 'freebase_id': 'tbd'},
    {'id': 100, 'name': 'Rhagionidae', 'freebase_id': 'tbd'},
    {'id': 101, 'name': 'Tortricidae', 'freebase_id': 'tbd'},
    {'id': 102, 'name': 'Coccinellidae', 'freebase_id': 'tbd'},
    {'id': 103, 'name': 'Pieridae', 'freebase_id': 'tbd'},
    {'id': 104, 'name': 'Syrphidae', 'freebase_id': 'tbd'},
    {'id': 105, 'name': 'Corydalidae', 'freebase_id': 'tbd'},
    {'id': 106, 'name': 'Scarabaeidae', 'freebase_id': 'tbd'},
    {'id': 107, 'name': 'Crambidae', 'freebase_id': 'tbd'},
    {'id': 108, 'name': 'Ulidiidae', 'freebase_id': 'tbd'},
    {'id': 109, 'name': 'Vespidae', 'freebase_id': 'tbd'},
    {'id': 110, 'name': 'Drepanidae', 'freebase_id': 'tbd'},
    {'id': 111, 'name': 'Gomphidae', 'freebase_id': 'tbd'},
    {'id': 112, 'name': 'Saturniidae', 'freebase_id': 'tbd'},
    {'id': 113, 'name': 'Sciuridae', 'freebase_id': 'tbd'},
    {'id': 114, 'name': 'Antilocapridae', 'freebase_id': 'tbd'},
    {'id': 115, 'name': 'Otariidae', 'freebase_id': 'tbd'},
    {'id': 116, 'name': 'Procyonidae', 'freebase_id': 'tbd'},
    {'id': 117, 'name': 'Bovidae', 'freebase_id': 'tbd'},
    {'id': 118, 'name': 'Canidae', 'freebase_id': 'tbd'},
    {'id': 119, 'name': 'Cervidae', 'freebase_id': 'tbd'},
    {'id': 120, 'name': 'Castoridae', 'freebase_id': 'tbd'},
    {'id': 121, 'name': 'Dasypodidae', 'freebase_id': 'tbd'},
    {'id': 122, 'name': 'Didelphidae', 'freebase_id': 'tbd'},
    {'id': 123, 'name': 'Mustelidae', 'freebase_id': 'tbd'},
    {'id': 124, 'name': 'Erethizontidae', 'freebase_id': 'tbd'},
    {'id': 125, 'name': 'Erinaceidae', 'freebase_id': 'tbd'},
    {'id': 126, 'name': 'Felidae', 'freebase_id': 'tbd'},
    {'id': 127, 'name': 'Leporidae', 'freebase_id': 'tbd'},
    {'id': 128, 'name': 'Elephantidae', 'freebase_id': 'tbd'},
    {'id': 129, 'name': 'Balaenopteridae', 'freebase_id': 'tbd'},
    {'id': 130, 'name': 'Mephitidae', 'freebase_id': 'tbd'},
    {'id': 131, 'name': 'Phocidae', 'freebase_id': 'tbd'},
    {'id': 132, 'name': 'Echimyidae', 'freebase_id': 'tbd'},
    {'id': 133, 'name': 'Ochotonidae', 'freebase_id': 'tbd'},
    {'id': 134, 'name': 'Cricetidae', 'freebase_id': 'tbd'},
    {'id': 135, 'name': 'Tayassuidae', 'freebase_id': 'tbd'},
    {'id': 136, 'name': 'Suidae', 'freebase_id': 'tbd'},
    {'id': 137, 'name': 'Geomyidae', 'freebase_id': 'tbd'},
    {'id': 138, 'name': 'Delphinidae', 'freebase_id': 'tbd'},
    {'id': 139, 'name': 'Ursidae', 'freebase_id': 'tbd'},
    {'id': 140, 'name': 'Onchidorididae', 'freebase_id': 'tbd'},
    {'id': 141, 'name': 'Aplysiidae', 'freebase_id': 'tbd'},
    {'id': 142, 'name': 'Ariolimacidae', 'freebase_id': 'tbd'},
    {'id': 143, 'name': 'Calliostomatidae', 'freebase_id': 'tbd'},
    {'id': 144, 'name': 'Helicidae', 'freebase_id': 'tbd'},
    {'id': 145, 'name': 'Cyrenidae', 'freebase_id': 'tbd'},
    {'id': 146, 'name': 'Acanthochitonidae', 'freebase_id': 'tbd'},
    {'id': 147, 'name': 'Agriolimacidae', 'freebase_id': 'tbd'},
    {'id': 148, 'name': 'Dorididae', 'freebase_id': 'tbd'},
    {'id': 149, 'name': 'Discodorididae', 'freebase_id': 'tbd'},
    {'id': 150, 'name': 'Myrrhinidae', 'freebase_id': 'tbd'},
    {'id': 151, 'name': 'Veneridae', 'freebase_id': 'tbd'},
    {'id': 152, 'name': 'Limacidae', 'freebase_id': 'tbd'},
    {'id': 153, 'name': 'Goniodorididae', 'freebase_id': 'tbd'},
    {'id': 154, 'name': 'Facelinidae', 'freebase_id': 'tbd'},
    {'id': 155, 'name': 'Achatinidae', 'freebase_id': 'tbd'},
    {'id': 156, 'name': 'Polyceridae', 'freebase_id': 'tbd'},
    {'id': 157, 'name': 'Emydidae', 'freebase_id': 'tbd'},
    {'id': 158, 'name': 'Alligatoridae', 'freebase_id': 'tbd'},
    {'id': 159, 'name': 'Anguidae', 'freebase_id': 'tbd'},
    {'id': 160, 'name': 'Dactyloidae', 'freebase_id': 'tbd'},
    {'id': 161, 'name': 'Trionychidae', 'freebase_id': 'tbd'},
    {'id': 162, 'name': 'Colubridae', 'freebase_id': 'tbd'},
    {'id': 163, 'name': 'Teiidae', 'freebase_id': 'tbd'},
    {'id': 164, 'name': 'Corytophanidae', 'freebase_id': 'tbd'},
    {'id': 165, 'name': 'Phrynosomatidae', 'freebase_id': 'tbd'},
    {'id': 166, 'name': 'Agamidae', 'freebase_id': 'tbd'},
    {'id': 167, 'name': 'Boidae', 'freebase_id': 'tbd'},
    {'id': 168, 'name': 'Cheloniidae', 'freebase_id': 'tbd'},
    {'id': 169, 'name': 'Chelydridae', 'freebase_id': 'tbd'},
    {'id': 170, 'name': 'Eublepharidae', 'freebase_id': 'tbd'},
    {'id': 171, 'name': 'Crocodylidae', 'freebase_id': 'tbd'},
    {'id': 172, 'name': 'Viperidae', 'freebase_id': 'tbd'},
    {'id': 173, 'name': 'Crotaphytidae', 'freebase_id': 'tbd'},
    {'id': 174, 'name': 'Iguanidae', 'freebase_id': 'tbd'},
    {'id': 175, 'name': 'Testudinidae', 'freebase_id': 'tbd'},
    {'id': 176, 'name': 'Helodermatidae', 'freebase_id': 'tbd'},
    {'id': 177, 'name': 'Gekkonidae', 'freebase_id': 'tbd'},
    {'id': 178, 'name': 'Kinosternidae', 'freebase_id': 'tbd'},
    {'id': 179, 'name': 'Elapidae', 'freebase_id': 'tbd'},
    {'id': 180, 'name': 'Scincidae', 'freebase_id': 'tbd'},
    {'id': 181, 'name': 'Lacertidae', 'freebase_id': 'tbd'},
    {'id': 182, 'name': 'Leptotyphlopidae', 'freebase_id': 'tbd'},
    {'id': 183, 'name': 'Sphenodontidae', 'freebase_id': 'tbd'},
    {'id': 184, 'name': 'Phyllodactylidae', 'freebase_id': 'tbd'}
]

# layer 5
# num_classes = 317
# layer: Genus
categories_l5 = [
    {'id': 1, 'name': 'Cyprinus', 'freebase_id': 'tbd'},
    {'id': 2, 'name': 'Lepomis', 'freebase_id': 'tbd'},
    {'id': 3, 'name': 'Micropterus', 'freebase_id': 'tbd'},
    {'id': 4, 'name': 'Oncorhynchus', 'freebase_id': 'tbd'},
    {'id': 5, 'name': 'Salvelinus', 'freebase_id': 'tbd'},
    {'id': 6, 'name': 'Zanclus', 'freebase_id': 'tbd'},
    {'id': 7, 'name': 'Acris', 'freebase_id': 'tbd'},
    {'id': 8, 'name': 'Ambystoma', 'freebase_id': 'tbd'},
    {'id': 9, 'name': 'Anaxyrus', 'freebase_id': 'tbd'},
    {'id': 10, 'name': 'Aneides', 'freebase_id': 'tbd'},
    {'id': 11, 'name': 'Batrachoseps', 'freebase_id': 'tbd'},
    {'id': 12, 'name': 'Bufo', 'freebase_id': 'tbd'},
    {'id': 13, 'name': 'Desmognathus', 'freebase_id': 'tbd'},
    {'id': 14, 'name': 'Dicamptodon', 'freebase_id': 'tbd'},
    {'id': 15, 'name': 'Eleutherodactylus', 'freebase_id': 'tbd'},
    {'id': 16, 'name': 'Ensatina', 'freebase_id': 'tbd'},
    {'id': 17, 'name': 'Eurycea', 'freebase_id': 'tbd'},
    {'id': 18, 'name': 'Gastrophryne', 'freebase_id': 'tbd'},
    {'id': 19, 'name': 'Hyla', 'freebase_id': 'tbd'},
    {'id': 20, 'name': 'Incilius', 'freebase_id': 'tbd'},
    {'id': 21, 'name': 'Lithobates', 'freebase_id': 'tbd'},
    {'id': 22, 'name': 'Notophthalmus', 'freebase_id': 'tbd'},
    {'id': 23, 'name': 'Oophaga', 'freebase_id': 'tbd'},
    {'id': 24, 'name': 'Osteopilus', 'freebase_id': 'tbd'},
    {'id': 25, 'name': 'Plethodon', 'freebase_id': 'tbd'},
    {'id': 26, 'name': 'Pseudacris', 'freebase_id': 'tbd'},
    {'id': 27, 'name': 'Rana', 'freebase_id': 'tbd'},
    {'id': 28, 'name': 'Salamandra', 'freebase_id': 'tbd'},
    {'id': 29, 'name': 'Scaphiopus', 'freebase_id': 'tbd'},
    {'id': 30, 'name': 'Smilisca', 'freebase_id': 'tbd'},
    {'id': 31, 'name': 'Spea', 'freebase_id': 'tbd'},
    {'id': 32, 'name': 'Taricha', 'freebase_id': 'tbd'},
    {'id': 33, 'name': 'Anthopleura', 'freebase_id': 'tbd'},
    {'id': 34, 'name': 'Armadillidium', 'freebase_id': 'tbd'},
    {'id': 35, 'name': 'Callinectes', 'freebase_id': 'tbd'},
    {'id': 36, 'name': 'Cancer', 'freebase_id': 'tbd'},
    {'id': 37, 'name': 'Dendraster', 'freebase_id': 'tbd'},
    {'id': 38, 'name': 'Dermasterias', 'freebase_id': 'tbd'},
    {'id': 39, 'name': 'Emerita', 'freebase_id': 'tbd'},
    {'id': 40, 'name': 'Epiactis', 'freebase_id': 'tbd'},
    {'id': 41, 'name': 'Harpaphe', 'freebase_id': 'tbd'},
    {'id': 42, 'name': 'Hemigrapsus', 'freebase_id': 'tbd'},
    {'id': 43, 'name': 'Limulus', 'freebase_id': 'tbd'},
    {'id': 44, 'name': 'Pachygrapsus', 'freebase_id': 'tbd'},
    {'id': 45, 'name': 'Patiria', 'freebase_id': 'tbd'},
    {'id': 46, 'name': 'Physalia', 'freebase_id': 'tbd'},
    {'id': 47, 'name': 'Pisaster', 'freebase_id': 'tbd'},
    {'id': 48, 'name': 'Procambarus', 'freebase_id': 'tbd'},
    {'id': 49, 'name': 'Pugettia', 'freebase_id': 'tbd'},
    {'id': 50, 'name': 'Scolopendra', 'freebase_id': 'tbd'},
    {'id': 51, 'name': 'Strongylocentrotus', 'freebase_id': 'tbd'},
    {'id': 52, 'name': 'Velella', 'freebase_id': 'tbd'},
    {'id': 53, 'name': 'Aphonopelma', 'freebase_id': 'tbd'},
    {'id': 54, 'name': 'Araneus', 'freebase_id': 'tbd'},
    {'id': 55, 'name': 'Argiope', 'freebase_id': 'tbd'},
    {'id': 56, 'name': 'Centruroides', 'freebase_id': 'tbd'},
    {'id': 57, 'name': 'Dermacentor', 'freebase_id': 'tbd'},
    {'id': 58, 'name': 'Dolomedes', 'freebase_id': 'tbd'},
    {'id': 59, 'name': 'Dysdera', 'freebase_id': 'tbd'},
    {'id': 60, 'name': 'Eriophora', 'freebase_id': 'tbd'},
    {'id': 61, 'name': 'Gasteracantha', 'freebase_id': 'tbd'},
    {'id': 62, 'name': 'Latrodectus', 'freebase_id': 'tbd'},
    {'id': 63, 'name': 'Micrathena', 'freebase_id': 'tbd'},
    {'id': 64, 'name': 'Misumena', 'freebase_id': 'tbd'},
    {'id': 65, 'name': 'Neoscona', 'freebase_id': 'tbd'},
    {'id': 66, 'name': 'Paraphidippus', 'freebase_id': 'tbd'},
    {'id': 67, 'name': 'Peucetia', 'freebase_id': 'tbd'},
    {'id': 68, 'name': 'Phidippus', 'freebase_id': 'tbd'},
    {'id': 69, 'name': 'Platycryptus', 'freebase_id': 'tbd'},
    {'id': 70, 'name': 'Salticus', 'freebase_id': 'tbd'},
    {'id': 71, 'name': 'Uroctonus', 'freebase_id': 'tbd'},
    {'id': 72, 'name': 'Verrucosa', 'freebase_id': 'tbd'},
    {'id': 73, 'name': 'Acridotheres', 'freebase_id': 'tbd'},
    {'id': 74, 'name': 'Actitis', 'freebase_id': 'tbd'},
    {'id': 75, 'name': 'Aechmophorus', 'freebase_id': 'tbd'},
    {'id': 76, 'name': 'Aegithalos', 'freebase_id': 'tbd'},
    {'id': 77, 'name': 'Agelaius', 'freebase_id': 'tbd'},
    {'id': 78, 'name': 'Aimophila', 'freebase_id': 'tbd'},
    {'id': 79, 'name': 'Aix', 'freebase_id': 'tbd'},
    {'id': 80, 'name': 'Alauda', 'freebase_id': 'tbd'},
    {'id': 81, 'name': 'Alcedo', 'freebase_id': 'tbd'},
    {'id': 82, 'name': 'Alopochen', 'freebase_id': 'tbd'},
    {'id': 83, 'name': 'Amazilia', 'freebase_id': 'tbd'},
    {'id': 84, 'name': 'Ammodramus', 'freebase_id': 'tbd'},
    {'id': 85, 'name': 'Amphispiza', 'freebase_id': 'tbd'},
    {'id': 86, 'name': 'Anas', 'freebase_id': 'tbd'},
    {'id': 87, 'name': 'Anhinga', 'freebase_id': 'tbd'},
    {'id': 88, 'name': 'Anthornis', 'freebase_id': 'tbd'},
    {'id': 89, 'name': 'Anthus', 'freebase_id': 'tbd'},
    {'id': 90, 'name': 'Antigone', 'freebase_id': 'tbd'},
    {'id': 91, 'name': 'Aphelocoma', 'freebase_id': 'tbd'},
    {'id': 92, 'name': 'Aquila', 'freebase_id': 'tbd'},
    {'id': 93, 'name': 'Aramus', 'freebase_id': 'tbd'},
    {'id': 94, 'name': 'Archilochus', 'freebase_id': 'tbd'},
    {'id': 95, 'name': 'Ardea', 'freebase_id': 'tbd'},
    {'id': 96, 'name': 'Ardenna', 'freebase_id': 'tbd'},
    {'id': 97, 'name': 'Arenaria', 'freebase_id': 'tbd'},
    {'id': 98, 'name': 'Asio', 'freebase_id': 'tbd'},
    {'id': 99, 'name': 'Athene', 'freebase_id': 'tbd'},
    {'id': 100, 'name': 'Auriparus', 'freebase_id': 'tbd'},
    {'id': 101, 'name': 'Aythya', 'freebase_id': 'tbd'},
    {'id': 102, 'name': 'Baeolophus', 'freebase_id': 'tbd'},
    {'id': 103, 'name': 'Bartramia', 'freebase_id': 'tbd'},
    {'id': 104, 'name': 'Basileuterus', 'freebase_id': 'tbd'},
    {'id': 105, 'name': 'Bombycilla', 'freebase_id': 'tbd'},
    {'id': 106, 'name': 'Bonasa', 'freebase_id': 'tbd'},
    {'id': 107, 'name': 'Botaurus', 'freebase_id': 'tbd'},
    {'id': 108, 'name': 'Branta', 'freebase_id': 'tbd'},
    {'id': 109, 'name': 'Bubo', 'freebase_id': 'tbd'},
    {'id': 110, 'name': 'Bubulcus', 'freebase_id': 'tbd'},
    {'id': 111, 'name': 'Bucephala', 'freebase_id': 'tbd'},
    {'id': 112, 'name': 'Buteo', 'freebase_id': 'tbd'},
    {'id': 113, 'name': 'Buteogallus', 'freebase_id': 'tbd'},
    {'id': 114, 'name': 'Butorides', 'freebase_id': 'tbd'},
    {'id': 115, 'name': 'Calidris', 'freebase_id': 'tbd'},
    {'id': 116, 'name': 'Callipepla', 'freebase_id': 'tbd'},
    {'id': 117, 'name': 'Calypte', 'freebase_id': 'tbd'},
    {'id': 118, 'name': 'Campephilus', 'freebase_id': 'tbd'},
    {'id': 119, 'name': 'Campylorhynchus', 'freebase_id': 'tbd'},
    {'id': 120, 'name': 'Caracara', 'freebase_id': 'tbd'},
    {'id': 121, 'name': 'Cardellina', 'freebase_id': 'tbd'},
    {'id': 122, 'name': 'Cardinalis', 'freebase_id': 'tbd'},
    {'id': 123, 'name': 'Carduelis', 'freebase_id': 'tbd'},
    {'id': 124, 'name': 'Cassiculus', 'freebase_id': 'tbd'},
    {'id': 125, 'name': 'Cathartes', 'freebase_id': 'tbd'},
    {'id': 126, 'name': 'Catharus', 'freebase_id': 'tbd'},
    {'id': 127, 'name': 'Catherpes', 'freebase_id': 'tbd'},
    {'id': 128, 'name': 'Cepphus', 'freebase_id': 'tbd'},
    {'id': 129, 'name': 'Certhia', 'freebase_id': 'tbd'},
    {'id': 130, 'name': 'Chamaea', 'freebase_id': 'tbd'},
    {'id': 131, 'name': 'Charadrius', 'freebase_id': 'tbd'},
    {'id': 132, 'name': 'Battus', 'freebase_id': 'tbd'},
    {'id': 133, 'name': 'Boisea', 'freebase_id': 'tbd'},
    {'id': 134, 'name': 'Boloria', 'freebase_id': 'tbd'},
    {'id': 135, 'name': 'Bombus', 'freebase_id': 'tbd'},
    {'id': 136, 'name': 'Bombylius', 'freebase_id': 'tbd'},
    {'id': 137, 'name': 'Brachymesia', 'freebase_id': 'tbd'},
    {'id': 138, 'name': 'Brechmorhoga', 'freebase_id': 'tbd'},
    {'id': 139, 'name': 'Brephidium', 'freebase_id': 'tbd'},
    {'id': 140, 'name': 'Caenurgina', 'freebase_id': 'tbd'},
    {'id': 141, 'name': 'Calephelis', 'freebase_id': 'tbd'},
    {'id': 142, 'name': 'Callophrys', 'freebase_id': 'tbd'},
    {'id': 143, 'name': 'Calopteron', 'freebase_id': 'tbd'},
    {'id': 144, 'name': 'Calopteryx', 'freebase_id': 'tbd'},
    {'id': 145, 'name': 'Calosoma', 'freebase_id': 'tbd'},
    {'id': 146, 'name': 'Calpodes', 'freebase_id': 'tbd'},
    {'id': 147, 'name': 'Calycopis', 'freebase_id': 'tbd'},
    {'id': 148, 'name': 'Campaea', 'freebase_id': 'tbd'},
    {'id': 149, 'name': 'Celastrina', 'freebase_id': 'tbd'},
    {'id': 150, 'name': 'Celithemis', 'freebase_id': 'tbd'},
    {'id': 151, 'name': 'Ceratomia', 'freebase_id': 'tbd'},
    {'id': 152, 'name': 'Cercyonis', 'freebase_id': 'tbd'},
    {'id': 153, 'name': 'Chauliognathus', 'freebase_id': 'tbd'},
    {'id': 154, 'name': 'Chinavia', 'freebase_id': 'tbd'},
    {'id': 155, 'name': 'Chioides', 'freebase_id': 'tbd'},
    {'id': 156, 'name': 'Chlorochlamys', 'freebase_id': 'tbd'},
    {'id': 157, 'name': 'Chlosyne', 'freebase_id': 'tbd'},
    {'id': 158, 'name': 'Chrysochus', 'freebase_id': 'tbd'},
    {'id': 159, 'name': 'Chrysopilus', 'freebase_id': 'tbd'},
    {'id': 160, 'name': 'Cicindela', 'freebase_id': 'tbd'},
    {'id': 161, 'name': 'Cisseps', 'freebase_id': 'tbd'},
    {'id': 162, 'name': 'Clepsis', 'freebase_id': 'tbd'},
    {'id': 163, 'name': 'Coccinella', 'freebase_id': 'tbd'},
    {'id': 164, 'name': 'Coenonympha', 'freebase_id': 'tbd'},
    {'id': 165, 'name': 'Coleomegilla', 'freebase_id': 'tbd'},
    {'id': 166, 'name': 'Colias', 'freebase_id': 'tbd'},
    {'id': 167, 'name': 'Copaeodes', 'freebase_id': 'tbd'},
    {'id': 168, 'name': 'Copestylum', 'freebase_id': 'tbd'},
    {'id': 169, 'name': 'Corydalus', 'freebase_id': 'tbd'},
    {'id': 170, 'name': 'Costaconvexa', 'freebase_id': 'tbd'},
    {'id': 171, 'name': 'Cotinis', 'freebase_id': 'tbd'},
    {'id': 172, 'name': 'Crambus', 'freebase_id': 'tbd'},
    {'id': 173, 'name': 'Crocothemis', 'freebase_id': 'tbd'},
    {'id': 174, 'name': 'Ctenucha', 'freebase_id': 'tbd'},
    {'id': 175, 'name': 'Cupido', 'freebase_id': 'tbd'},
    {'id': 176, 'name': 'Cycloneda', 'freebase_id': 'tbd'},
    {'id': 177, 'name': 'Cydia', 'freebase_id': 'tbd'},
    {'id': 178, 'name': 'Danaus', 'freebase_id': 'tbd'},
    {'id': 179, 'name': 'Darapsa', 'freebase_id': 'tbd'},
    {'id': 180, 'name': 'Delphinia', 'freebase_id': 'tbd'},
    {'id': 181, 'name': 'Diabrotica', 'freebase_id': 'tbd'},
    {'id': 182, 'name': 'Dione', 'freebase_id': 'tbd'},
    {'id': 183, 'name': 'Dioprosopa', 'freebase_id': 'tbd'},
    {'id': 184, 'name': 'Dolichovespula', 'freebase_id': 'tbd'},
    {'id': 185, 'name': 'Drepana', 'freebase_id': 'tbd'},
    {'id': 186, 'name': 'Dromogomphus', 'freebase_id': 'tbd'},
    {'id': 187, 'name': 'Dryas', 'freebase_id': 'tbd'},
    {'id': 188, 'name': 'Dryocampa', 'freebase_id': 'tbd'},
    {'id': 189, 'name': 'Dythemis', 'freebase_id': 'tbd'},
    {'id': 190, 'name': 'Ammospermophilus', 'freebase_id': 'tbd'},
    {'id': 191, 'name': 'Antilocapra', 'freebase_id': 'tbd'},
    {'id': 192, 'name': 'Arctocephalus', 'freebase_id': 'tbd'},
    {'id': 193, 'name': 'Bassariscus', 'freebase_id': 'tbd'},
    {'id': 194, 'name': 'Bison', 'freebase_id': 'tbd'},
    {'id': 195, 'name': 'Callospermophilus', 'freebase_id': 'tbd'},
    {'id': 196, 'name': 'Canis', 'freebase_id': 'tbd'},
    {'id': 197, 'name': 'Capreolus', 'freebase_id': 'tbd'},
    {'id': 198, 'name': 'Castor', 'freebase_id': 'tbd'},
    {'id': 199, 'name': 'Cynomys', 'freebase_id': 'tbd'},
    {'id': 200, 'name': 'Dasypus', 'freebase_id': 'tbd'},
    {'id': 201, 'name': 'Didelphis', 'freebase_id': 'tbd'},
    {'id': 202, 'name': 'Enhydra', 'freebase_id': 'tbd'},
    {'id': 203, 'name': 'Erethizon', 'freebase_id': 'tbd'},
    {'id': 204, 'name': 'Erinaceus', 'freebase_id': 'tbd'},
    {'id': 205, 'name': 'Felis', 'freebase_id': 'tbd'},
    {'id': 206, 'name': 'Lepus', 'freebase_id': 'tbd'},
    {'id': 207, 'name': 'Lontra', 'freebase_id': 'tbd'},
    {'id': 208, 'name': 'Loxodonta', 'freebase_id': 'tbd'},
    {'id': 209, 'name': 'Lynx', 'freebase_id': 'tbd'},
    {'id': 210, 'name': 'Marmota', 'freebase_id': 'tbd'},
    {'id': 211, 'name': 'Megaptera', 'freebase_id': 'tbd'},
    {'id': 212, 'name': 'Mephitis', 'freebase_id': 'tbd'},
    {'id': 213, 'name': 'Mirounga', 'freebase_id': 'tbd'},
    {'id': 214, 'name': 'Myocastor', 'freebase_id': 'tbd'},
    {'id': 215, 'name': 'Nasua', 'freebase_id': 'tbd'},
    {'id': 216, 'name': 'Neovison', 'freebase_id': 'tbd'},
    {'id': 217, 'name': 'Ochotona', 'freebase_id': 'tbd'},
    {'id': 218, 'name': 'Odocoileus', 'freebase_id': 'tbd'},
    {'id': 219, 'name': 'Ondatra', 'freebase_id': 'tbd'},
    {'id': 220, 'name': 'Oryctolagus', 'freebase_id': 'tbd'},
    {'id': 221, 'name': 'Otospermophilus', 'freebase_id': 'tbd'},
    {'id': 222, 'name': 'Ovis', 'freebase_id': 'tbd'},
    {'id': 223, 'name': 'Panthera', 'freebase_id': 'tbd'},
    {'id': 224, 'name': 'Pecari', 'freebase_id': 'tbd'},
    {'id': 225, 'name': 'Phoca', 'freebase_id': 'tbd'},
    {'id': 226, 'name': 'Procyon', 'freebase_id': 'tbd'},
    {'id': 227, 'name': 'Sciurus', 'freebase_id': 'tbd'},
    {'id': 228, 'name': 'Sus', 'freebase_id': 'tbd'},
    {'id': 229, 'name': 'Sylvilagus', 'freebase_id': 'tbd'},
    {'id': 230, 'name': 'Tamias', 'freebase_id': 'tbd'},
    {'id': 231, 'name': 'Tamiasciurus', 'freebase_id': 'tbd'},
    {'id': 232, 'name': 'Thomomys', 'freebase_id': 'tbd'},
    {'id': 233, 'name': 'Tursiops', 'freebase_id': 'tbd'},
    {'id': 234, 'name': 'Urocyon', 'freebase_id': 'tbd'},
    {'id': 235, 'name': 'Ursus', 'freebase_id': 'tbd'},
    {'id': 236, 'name': 'Vulpes', 'freebase_id': 'tbd'},
    {'id': 237, 'name': 'Zalophus', 'freebase_id': 'tbd'},
    {'id': 238, 'name': 'Acanthodoris', 'freebase_id': 'tbd'},
    {'id': 239, 'name': 'Aplysia', 'freebase_id': 'tbd'},
    {'id': 240, 'name': 'Ariolimax', 'freebase_id': 'tbd'},
    {'id': 241, 'name': 'Calliostoma', 'freebase_id': 'tbd'},
    {'id': 242, 'name': 'Cepaea', 'freebase_id': 'tbd'},
    {'id': 243, 'name': 'Corbicula', 'freebase_id': 'tbd'},
    {'id': 244, 'name': 'Cornu', 'freebase_id': 'tbd'},
    {'id': 245, 'name': 'Cryptochiton', 'freebase_id': 'tbd'},
    {'id': 246, 'name': 'Deroceras', 'freebase_id': 'tbd'},
    {'id': 247, 'name': 'Doris', 'freebase_id': 'tbd'},
    {'id': 248, 'name': 'Geitodoris', 'freebase_id': 'tbd'},
    {'id': 249, 'name': 'Hermissenda', 'freebase_id': 'tbd'},
    {'id': 250, 'name': 'Leukoma', 'freebase_id': 'tbd'},
    {'id': 251, 'name': 'Limax', 'freebase_id': 'tbd'},
    {'id': 252, 'name': 'Okenia', 'freebase_id': 'tbd'},
    {'id': 253, 'name': 'Otala', 'freebase_id': 'tbd'},
    {'id': 254, 'name': 'Peltodoris', 'freebase_id': 'tbd'},
    {'id': 255, 'name': 'Phidiana', 'freebase_id': 'tbd'},
    {'id': 256, 'name': 'Rumina', 'freebase_id': 'tbd'},
    {'id': 257, 'name': 'Triopha', 'freebase_id': 'tbd'},
    {'id': 258, 'name': 'Actinemys', 'freebase_id': 'tbd'},
    {'id': 259, 'name': 'Alligator', 'freebase_id': 'tbd'},
    {'id': 260, 'name': 'Anguis', 'freebase_id': 'tbd'},
    {'id': 261, 'name': 'Anolis', 'freebase_id': 'tbd'},
    {'id': 262, 'name': 'Apalone', 'freebase_id': 'tbd'},
    {'id': 263, 'name': 'Arizona', 'freebase_id': 'tbd'},
    {'id': 264, 'name': 'Aspidoscelis', 'freebase_id': 'tbd'},
    {'id': 265, 'name': 'Basiliscus', 'freebase_id': 'tbd'},
    {'id': 266, 'name': 'Callisaurus', 'freebase_id': 'tbd'},
    {'id': 267, 'name': 'Calotes', 'freebase_id': 'tbd'},
    {'id': 268, 'name': 'Charina', 'freebase_id': 'tbd'},
    {'id': 269, 'name': 'Chelonia', 'freebase_id': 'tbd'},
    {'id': 270, 'name': 'Chelydra', 'freebase_id': 'tbd'},
    {'id': 271, 'name': 'Chrysemys', 'freebase_id': 'tbd'},
    {'id': 272, 'name': 'Coleonyx', 'freebase_id': 'tbd'},
    {'id': 273, 'name': 'Coluber', 'freebase_id': 'tbd'},
    {'id': 274, 'name': 'Cophosaurus', 'freebase_id': 'tbd'},
    {'id': 275, 'name': 'Crocodylus', 'freebase_id': 'tbd'},
    {'id': 276, 'name': 'Crotalus', 'freebase_id': 'tbd'},
    {'id': 277, 'name': 'Crotaphytus', 'freebase_id': 'tbd'},
    {'id': 278, 'name': 'Ctenosaura', 'freebase_id': 'tbd'},
    {'id': 279, 'name': 'Diadophis', 'freebase_id': 'tbd'},
    {'id': 280, 'name': 'Dipsosaurus', 'freebase_id': 'tbd'},
    {'id': 281, 'name': 'Elgaria', 'freebase_id': 'tbd'},
    {'id': 282, 'name': 'Eretmochelys', 'freebase_id': 'tbd'},
    {'id': 283, 'name': 'Gopherus', 'freebase_id': 'tbd'},
    {'id': 284, 'name': 'Heloderma', 'freebase_id': 'tbd'},
    {'id': 285, 'name': 'Hemidactylus', 'freebase_id': 'tbd'},
    {'id': 286, 'name': 'Heterodon', 'freebase_id': 'tbd'},
    {'id': 287, 'name': 'Hypsiglena', 'freebase_id': 'tbd'},
    {'id': 288, 'name': 'Iguana', 'freebase_id': 'tbd'},
    {'id': 289, 'name': 'Kinosternon', 'freebase_id': 'tbd'},
    {'id': 290, 'name': 'Lampropeltis', 'freebase_id': 'tbd'},
    {'id': 291, 'name': 'Micrurus', 'freebase_id': 'tbd'},
    {'id': 292, 'name': 'Nerodia', 'freebase_id': 'tbd'},
    {'id': 293, 'name': 'Opheodrys', 'freebase_id': 'tbd'},
    {'id': 294, 'name': 'Pantherophis', 'freebase_id': 'tbd'},
    {'id': 295, 'name': 'Phelsuma', 'freebase_id': 'tbd'},
    {'id': 296, 'name': 'Phrynosoma', 'freebase_id': 'tbd'},
    {'id': 297, 'name': 'Pituophis', 'freebase_id': 'tbd'},
    {'id': 298, 'name': 'Plestiodon', 'freebase_id': 'tbd'},
    {'id': 299, 'name': 'Podarcis', 'freebase_id': 'tbd'},
    {'id': 300, 'name': 'Pseudemys', 'freebase_id': 'tbd'},
    {'id': 301, 'name': 'Rena', 'freebase_id': 'tbd'},
    {'id': 302, 'name': 'Rhinocheilus', 'freebase_id': 'tbd'},
    {'id': 303, 'name': 'Sauromalus', 'freebase_id': 'tbd'},
    {'id': 304, 'name': 'Sceloporus', 'freebase_id': 'tbd'},
    {'id': 305, 'name': 'Scincella', 'freebase_id': 'tbd'},
    {'id': 306, 'name': 'Sonora', 'freebase_id': 'tbd'},
    {'id': 307, 'name': 'Sphenodon', 'freebase_id': 'tbd'},
    {'id': 308, 'name': 'Sternotherus', 'freebase_id': 'tbd'},
    {'id': 309, 'name': 'Storeria', 'freebase_id': 'tbd'},
    {'id': 310, 'name': 'Tantilla', 'freebase_id': 'tbd'},
    {'id': 311, 'name': 'Tarentola', 'freebase_id': 'tbd'},
    {'id': 312, 'name': 'Terrapene', 'freebase_id': 'tbd'},
    {'id': 313, 'name': 'Thamnophis', 'freebase_id': 'tbd'},
    {'id': 314, 'name': 'Trachemys', 'freebase_id': 'tbd'},
    {'id': 315, 'name': 'Urosaurus', 'freebase_id': 'tbd'},
    {'id': 316, 'name': 'Uta', 'freebase_id': 'tbd'},
    {'id': 317, 'name': 'Zootoca', 'freebase_id': 'tbd'},
]

# layer
# num_classes = 500
# layer: Species
categories =[
    {'id': 1, 'name': 'Cyprinus carpio', 'freebase_id': 'tbd'},
    {'id': 2, 'name': 'Lepomis cyanellus', 'freebase_id': 'tbd'},
    {'id': 3, 'name': 'Lepomis macrochirus', 'freebase_id': 'tbd'},
    {'id': 4, 'name': 'Micropterus salmoides', 'freebase_id': 'tbd'},
    {'id': 5, 'name': 'Oncorhynchus mykiss', 'freebase_id': 'tbd'},
    {'id': 6, 'name': 'Salvelinus fontinalis', 'freebase_id': 'tbd'},
    {'id': 7, 'name': 'Zanclus cornutus', 'freebase_id': 'tbd'},
    {'id': 8, 'name': 'Acris blanchardi', 'freebase_id': 'tbd'},
    {'id': 9, 'name': 'Ambystoma laterale', 'freebase_id': 'tbd'},
    {'id': 10, 'name': 'Ambystoma maculatum', 'freebase_id': 'tbd'},
    {'id': 11, 'name': 'Ambystoma opacum', 'freebase_id': 'tbd'},
    {'id': 12, 'name': 'Anaxyrus americanus', 'freebase_id': 'tbd'},
    {'id': 13, 'name': 'Anaxyrus boreas', 'freebase_id': 'tbd'},
    {'id': 14, 'name': 'Anaxyrus cognatus', 'freebase_id': 'tbd'},
    {'id': 15, 'name': 'Anaxyrus fowleri', 'freebase_id': 'tbd'},
    {'id': 16, 'name': 'Anaxyrus punctatus', 'freebase_id': 'tbd'},
    {'id': 17, 'name': 'Anaxyrus speciosus', 'freebase_id': 'tbd'},
    {'id': 18, 'name': 'Anaxyrus terrestris', 'freebase_id': 'tbd'},
    {'id': 19, 'name': 'Anaxyrus woodhousii', 'freebase_id': 'tbd'},
    {'id': 20, 'name': 'Aneides lugubris', 'freebase_id': 'tbd'},
    {'id': 21, 'name': 'Batrachoseps attenuatus', 'freebase_id': 'tbd'},
    {'id': 22, 'name': 'Batrachoseps major', 'freebase_id': 'tbd'},
    {'id': 23, 'name': 'Batrachoseps nigriventris', 'freebase_id': 'tbd'},
    {'id': 24, 'name': 'Bufo bufo', 'freebase_id': 'tbd'},
    {'id': 25, 'name': 'Desmognathus fuscus', 'freebase_id': 'tbd'},
    {'id': 26, 'name': 'Dicamptodon ensatus', 'freebase_id': 'tbd'},
    {'id': 27, 'name': 'Eleutherodactylus cystignathoides', 'freebase_id': 'tbd'},
    {'id': 28, 'name': 'Ensatina eschscholtzii', 'freebase_id': 'tbd'},
    {'id': 29, 'name': 'Eurycea bislineata', 'freebase_id': 'tbd'},
    {'id': 30, 'name': 'Gastrophryne carolinensis', 'freebase_id': 'tbd'},
    {'id': 31, 'name': 'Gastrophryne olivacea', 'freebase_id': 'tbd'},
    {'id': 32, 'name': 'Hyla arenicolor', 'freebase_id': 'tbd'},
    {'id': 33, 'name': 'Hyla chrysoscelis', 'freebase_id': 'tbd'},
    {'id': 34, 'name': 'Hyla cinerea', 'freebase_id': 'tbd'},
    {'id': 35, 'name': 'Hyla eximia', 'freebase_id': 'tbd'},
    {'id': 36, 'name': 'Hyla squirella', 'freebase_id': 'tbd'},
    {'id': 37, 'name': 'Hyla versicolor', 'freebase_id': 'tbd'},
    {'id': 38, 'name': 'Incilius nebulifer', 'freebase_id': 'tbd'},
    {'id': 39, 'name': 'Lithobates berlandieri', 'freebase_id': 'tbd'},
    {'id': 40, 'name': 'Lithobates blairi', 'freebase_id': 'tbd'},
    {'id': 41, 'name': 'Lithobates catesbeianus', 'freebase_id': 'tbd'},
    {'id': 42, 'name': 'Lithobates clamitans', 'freebase_id': 'tbd'},
    {'id': 43, 'name': 'Lithobates palustris', 'freebase_id': 'tbd'},
    {'id': 44, 'name': 'Lithobates pipiens', 'freebase_id': 'tbd'},
    {'id': 45, 'name': 'Lithobates sphenocephalus', 'freebase_id': 'tbd'},
    {'id': 46, 'name': 'Lithobates sylvaticus', 'freebase_id': 'tbd'},
    {'id': 47, 'name': 'Notophthalmus viridescens', 'freebase_id': 'tbd'},
    {'id': 48, 'name': 'Oophaga pumilio', 'freebase_id': 'tbd'},
    {'id': 49, 'name': 'Osteopilus septentrionalis', 'freebase_id': 'tbd'},
    {'id': 50, 'name': 'Plethodon albagula', 'freebase_id': 'tbd'},
    {'id': 51, 'name': 'Plethodon cinereus', 'freebase_id': 'tbd'},
    {'id': 52, 'name': 'Plethodon glutinosus', 'freebase_id': 'tbd'},
    {'id': 53, 'name': 'Pseudacris cadaverina', 'freebase_id': 'tbd'},
    {'id': 54, 'name': 'Pseudacris crucifer', 'freebase_id': 'tbd'},
    {'id': 55, 'name': 'Pseudacris hypochondriaca', 'freebase_id': 'tbd'},
    {'id': 56, 'name': 'Pseudacris regilla', 'freebase_id': 'tbd'},
    {'id': 57, 'name': 'Pseudacris sierra', 'freebase_id': 'tbd'},
    {'id': 58, 'name': 'Rana aurora', 'freebase_id': 'tbd'},
    {'id': 59, 'name': 'Rana boylii', 'freebase_id': 'tbd'},
    {'id': 60, 'name': 'Rana draytonii', 'freebase_id': 'tbd'},
    {'id': 61, 'name': 'Rana temporaria', 'freebase_id': 'tbd'},
    {'id': 62, 'name': 'Salamandra salamandra', 'freebase_id': 'tbd'},
    {'id': 63, 'name': 'Scaphiopus couchii', 'freebase_id': 'tbd'},
    {'id': 64, 'name': 'Smilisca baudinii', 'freebase_id': 'tbd'},
    {'id': 65, 'name': 'Spea multiplicata', 'freebase_id': 'tbd'},
    {'id': 66, 'name': 'Taricha granulosa', 'freebase_id': 'tbd'},
    {'id': 67, 'name': 'Taricha torosa', 'freebase_id': 'tbd'},
    {'id': 68, 'name': 'Anthopleura artemisia', 'freebase_id': 'tbd'},
    {'id': 69, 'name': 'Anthopleura sola', 'freebase_id': 'tbd'},
    {'id': 70, 'name': 'Anthopleura xanthogrammica', 'freebase_id': 'tbd'},
    {'id': 71, 'name': 'Armadillidium vulgare', 'freebase_id': 'tbd'},
    {'id': 72, 'name': 'Callinectes sapidus', 'freebase_id': 'tbd'},
    {'id': 73, 'name': 'Cancer productus', 'freebase_id': 'tbd'},
    {'id': 74, 'name': 'Dendraster excentricus', 'freebase_id': 'tbd'},
    {'id': 75, 'name': 'Dermasterias imbricata', 'freebase_id': 'tbd'},
    {'id': 76, 'name': 'Emerita analoga', 'freebase_id': 'tbd'},
    {'id': 77, 'name': 'Epiactis prolifera', 'freebase_id': 'tbd'},
    {'id': 78, 'name': 'Harpaphe haydeniana', 'freebase_id': 'tbd'},
    {'id': 79, 'name': 'Hemigrapsus oregonensis', 'freebase_id': 'tbd'},
    {'id': 80, 'name': 'Limulus polyphemus', 'freebase_id': 'tbd'},
    {'id': 81, 'name': 'Pachygrapsus crassipes', 'freebase_id': 'tbd'},
    {'id': 82, 'name': 'Patiria miniata', 'freebase_id': 'tbd'},
    {'id': 83, 'name': 'Physalia physalis', 'freebase_id': 'tbd'},
    {'id': 84, 'name': 'Pisaster ochraceus', 'freebase_id': 'tbd'},
    {'id': 85, 'name': 'Procambarus clarkii', 'freebase_id': 'tbd'},
    {'id': 86, 'name': 'Pugettia producta', 'freebase_id': 'tbd'},
    {'id': 87, 'name': 'Scolopendra polymorpha', 'freebase_id': 'tbd'},
    {'id': 88, 'name': 'Strongylocentrotus purpuratus', 'freebase_id': 'tbd'},
    {'id': 89, 'name': 'Velella velella', 'freebase_id': 'tbd'},
    {'id': 90, 'name': 'Aphonopelma hentzi', 'freebase_id': 'tbd'},
    {'id': 91, 'name': 'Araneus diadematus', 'freebase_id': 'tbd'},
    {'id': 92, 'name': 'Argiope argentata', 'freebase_id': 'tbd'},
    {'id': 93, 'name': 'Argiope aurantia', 'freebase_id': 'tbd'},
    {'id': 94, 'name': 'Argiope trifasciata', 'freebase_id': 'tbd'},
    {'id': 95, 'name': 'Centruroides vittatus', 'freebase_id': 'tbd'},
    {'id': 96, 'name': 'Dermacentor variabilis', 'freebase_id': 'tbd'},
    {'id': 97, 'name': 'Dolomedes minor', 'freebase_id': 'tbd'},
    {'id': 98, 'name': 'Dysdera crocata', 'freebase_id': 'tbd'},
    {'id': 99, 'name': 'Eriophora pustulosa', 'freebase_id': 'tbd'},
    {'id': 100, 'name': 'Gasteracantha cancriformis', 'freebase_id': 'tbd'},
    {'id': 101, 'name': 'Latrodectus geometricus', 'freebase_id': 'tbd'},
    {'id': 102, 'name': 'Latrodectus hesperus', 'freebase_id': 'tbd'},
    {'id': 103, 'name': 'Latrodectus mactans', 'freebase_id': 'tbd'},
    {'id': 104, 'name': 'Micrathena gracilis', 'freebase_id': 'tbd'},
    {'id': 105, 'name': 'Misumena vatia', 'freebase_id': 'tbd'},
    {'id': 106, 'name': 'Neoscona crucifera', 'freebase_id': 'tbd'},
    {'id': 107, 'name': 'Neoscona oaxacensis', 'freebase_id': 'tbd'},
    {'id': 108, 'name': 'Paraphidippus aurantius', 'freebase_id': 'tbd'},
    {'id': 109, 'name': 'Peucetia viridans', 'freebase_id': 'tbd'},
    {'id': 110, 'name': 'Phidippus audax', 'freebase_id': 'tbd'},
    {'id': 111, 'name': 'Phidippus johnsoni', 'freebase_id': 'tbd'},
    {'id': 112, 'name': 'Platycryptus undatus', 'freebase_id': 'tbd'},
    {'id': 113, 'name': 'Salticus scenicus', 'freebase_id': 'tbd'},
    {'id': 114, 'name': 'Uroctonus mordax', 'freebase_id': 'tbd'},
    {'id': 115, 'name': 'Verrucosa arenata', 'freebase_id': 'tbd'},
    {'id': 116, 'name': 'Acridotheres tristis', 'freebase_id': 'tbd'},
    {'id': 117, 'name': 'Actitis hypoleucos', 'freebase_id': 'tbd'},
    {'id': 118, 'name': 'Actitis macularius', 'freebase_id': 'tbd'},
    {'id': 119, 'name': 'Aechmophorus clarkii', 'freebase_id': 'tbd'},
    {'id': 120, 'name': 'Aechmophorus occidentalis', 'freebase_id': 'tbd'},
    {'id': 121, 'name': 'Aegithalos caudatus', 'freebase_id': 'tbd'},
    {'id': 122, 'name': 'Agelaius phoeniceus', 'freebase_id': 'tbd'},
    {'id': 123, 'name': 'Aimophila ruficeps', 'freebase_id': 'tbd'},
    {'id': 124, 'name': 'Aix sponsa', 'freebase_id': 'tbd'},
    {'id': 125, 'name': 'Alauda arvensis', 'freebase_id': 'tbd'},
    {'id': 126, 'name': 'Alcedo atthis', 'freebase_id': 'tbd'},
    {'id': 127, 'name': 'Alopochen aegyptiaca', 'freebase_id': 'tbd'},
    {'id': 128, 'name': 'Amazilia rutila', 'freebase_id': 'tbd'},
    {'id': 129, 'name': 'Amazilia violiceps', 'freebase_id': 'tbd'},
    {'id': 130, 'name': 'Amazilia yucatanensis', 'freebase_id': 'tbd'},
    {'id': 131, 'name': 'Ammodramus savannarum', 'freebase_id': 'tbd'},
    {'id': 132, 'name': 'Amphispiza bilineata', 'freebase_id': 'tbd'},
    {'id': 133, 'name': 'Anas acuta', 'freebase_id': 'tbd'},
    {'id': 134, 'name': 'Anas crecca', 'freebase_id': 'tbd'},
    {'id': 135, 'name': 'Anas platyrhynchos', 'freebase_id': 'tbd'},
    {'id': 136, 'name': 'Anhinga anhinga', 'freebase_id': 'tbd'},
    {'id': 137, 'name': 'Anthornis melanura', 'freebase_id': 'tbd'},
    {'id': 138, 'name': 'Anthus rubescens', 'freebase_id': 'tbd'},
    {'id': 139, 'name': 'Antigone canadensis', 'freebase_id': 'tbd'},
    {'id': 140, 'name': 'Aphelocoma californica', 'freebase_id': 'tbd'},
    {'id': 141, 'name': 'Aphelocoma wollweberi', 'freebase_id': 'tbd'},
    {'id': 142, 'name': 'Aphelocoma woodhouseii', 'freebase_id': 'tbd'},
    {'id': 143, 'name': 'Aquila chrysaetos', 'freebase_id': 'tbd'},
    {'id': 144, 'name': 'Aramus guarauna', 'freebase_id': 'tbd'},
    {'id': 145, 'name': 'Archilochus alexandri', 'freebase_id': 'tbd'},
    {'id': 146, 'name': 'Archilochus colubris', 'freebase_id': 'tbd'},
    {'id': 147, 'name': 'Ardea alba', 'freebase_id': 'tbd'},
    {'id': 148, 'name': 'Ardea cinerea', 'freebase_id': 'tbd'},
    {'id': 149, 'name': 'Ardea herodias', 'freebase_id': 'tbd'},
    {'id': 150, 'name': 'Ardea purpurea', 'freebase_id': 'tbd'},
    {'id': 151, 'name': 'Ardenna creatopus', 'freebase_id': 'tbd'},
    {'id': 152, 'name': 'Arenaria interpres', 'freebase_id': 'tbd'},
    {'id': 153, 'name': 'Arenaria melanocephala', 'freebase_id': 'tbd'},
    {'id': 154, 'name': 'Asio flammeus', 'freebase_id': 'tbd'},
    {'id': 155, 'name': 'Asio otus', 'freebase_id': 'tbd'},
    {'id': 156, 'name': 'Athene cunicularia', 'freebase_id': 'tbd'},
    {'id': 157, 'name': 'Auriparus flaviceps', 'freebase_id': 'tbd'},
    {'id': 158, 'name': 'Aythya affinis', 'freebase_id': 'tbd'},
    {'id': 159, 'name': 'Aythya americana', 'freebase_id': 'tbd'},
    {'id': 160, 'name': 'Aythya collaris', 'freebase_id': 'tbd'},
    {'id': 161, 'name': 'Aythya fuligula', 'freebase_id': 'tbd'},
    {'id': 162, 'name': 'Aythya marila', 'freebase_id': 'tbd'},
    {'id': 163, 'name': 'Aythya valisineria', 'freebase_id': 'tbd'},
    {'id': 164, 'name': 'Baeolophus atricristatus', 'freebase_id': 'tbd'},
    {'id': 165, 'name': 'Baeolophus bicolor', 'freebase_id': 'tbd'},
    {'id': 166, 'name': 'Baeolophus inornatus', 'freebase_id': 'tbd'},
    {'id': 167, 'name': 'Bartramia longicauda', 'freebase_id': 'tbd'},
    {'id': 168, 'name': 'Basileuterus rufifrons', 'freebase_id': 'tbd'},
    {'id': 169, 'name': 'Bombycilla cedrorum', 'freebase_id': 'tbd'},
    {'id': 170, 'name': 'Bonasa umbellus', 'freebase_id': 'tbd'},
    {'id': 171, 'name': 'Botaurus lentiginosus', 'freebase_id': 'tbd'},
    {'id': 172, 'name': 'Branta bernicla', 'freebase_id': 'tbd'},
    {'id': 173, 'name': 'Branta canadensis', 'freebase_id': 'tbd'},
    {'id': 174, 'name': 'Bubo scandiacus', 'freebase_id': 'tbd'},
    {'id': 175, 'name': 'Bubo virginianus', 'freebase_id': 'tbd'},
    {'id': 176, 'name': 'Bubulcus ibis', 'freebase_id': 'tbd'},
    {'id': 177, 'name': 'Bucephala albeola', 'freebase_id': 'tbd'},
    {'id': 178, 'name': 'Bucephala clangula', 'freebase_id': 'tbd'},
    {'id': 179, 'name': 'Buteo albonotatus', 'freebase_id': 'tbd'},
    {'id': 180, 'name': 'Buteo buteo', 'freebase_id': 'tbd'},
    {'id': 181, 'name': 'Buteo jamaicensis', 'freebase_id': 'tbd'},
    {'id': 182, 'name': 'Buteo lagopus', 'freebase_id': 'tbd'},
    {'id': 183, 'name': 'Buteo lineatus', 'freebase_id': 'tbd'},
    {'id': 184, 'name': 'Buteo plagiatus', 'freebase_id': 'tbd'},
    {'id': 185, 'name': 'Buteo platypterus', 'freebase_id': 'tbd'},
    {'id': 186, 'name': 'Buteo regalis', 'freebase_id': 'tbd'},
    {'id': 187, 'name': 'Buteo swainsoni', 'freebase_id': 'tbd'},
    {'id': 188, 'name': 'Buteogallus anthracinus', 'freebase_id': 'tbd'},
    {'id': 189, 'name': 'Butorides striata', 'freebase_id': 'tbd'},
    {'id': 190, 'name': 'Butorides virescens', 'freebase_id': 'tbd'},
    {'id': 191, 'name': 'Calidris alba', 'freebase_id': 'tbd'},
    {'id': 192, 'name': 'Calidris alpina', 'freebase_id': 'tbd'},
    {'id': 193, 'name': 'Calidris bairdii', 'freebase_id': 'tbd'},
    {'id': 194, 'name': 'Calidris mauri', 'freebase_id': 'tbd'},
    {'id': 195, 'name': 'Calidris melanotos', 'freebase_id': 'tbd'},
    {'id': 196, 'name': 'Calidris minutilla', 'freebase_id': 'tbd'},
    {'id': 197, 'name': 'Calidris pusilla', 'freebase_id': 'tbd'},
    {'id': 198, 'name': 'Calidris virgata', 'freebase_id': 'tbd'},
    {'id': 199, 'name': 'Callipepla californica', 'freebase_id': 'tbd'},
    {'id': 200, 'name': 'Callipepla gambelii', 'freebase_id': 'tbd'},
    {'id': 201, 'name': 'Callipepla squamata', 'freebase_id': 'tbd'},
    {'id': 202, 'name': 'Calypte anna', 'freebase_id': 'tbd'},
    {'id': 203, 'name': 'Calypte costae', 'freebase_id': 'tbd'},
    {'id': 204, 'name': 'Campephilus guatemalensis', 'freebase_id': 'tbd'},
    {'id': 205, 'name': 'Campylorhynchus brunneicapillus', 'freebase_id': 'tbd'},
    {'id': 206, 'name': 'Caracara cheriway', 'freebase_id': 'tbd'},
    {'id': 207, 'name': 'Cardellina pusilla', 'freebase_id': 'tbd'},
    {'id': 208, 'name': 'Cardinalis cardinalis', 'freebase_id': 'tbd'},
    {'id': 209, 'name': 'Cardinalis sinuatus', 'freebase_id': 'tbd'},
    {'id': 210, 'name': 'Carduelis carduelis', 'freebase_id': 'tbd'},
    {'id': 211, 'name': 'Cassiculus melanicterus', 'freebase_id': 'tbd'},
    {'id': 212, 'name': 'Cathartes aura', 'freebase_id': 'tbd'},
    {'id': 213, 'name': 'Catharus fuscescens', 'freebase_id': 'tbd'},
    {'id': 214, 'name': 'Catharus guttatus', 'freebase_id': 'tbd'},
    {'id': 215, 'name': 'Catharus ustulatus', 'freebase_id': 'tbd'},
    {'id': 216, 'name': 'Catherpes mexicanus', 'freebase_id': 'tbd'},
    {'id': 217, 'name': 'Cepphus columba', 'freebase_id': 'tbd'},
    {'id': 218, 'name': 'Certhia americana', 'freebase_id': 'tbd'},
    {'id': 219, 'name': 'Chamaea fasciata', 'freebase_id': 'tbd'},
    {'id': 220, 'name': 'Charadrius melodus', 'freebase_id': 'tbd'},
    {'id': 221, 'name': 'Charadrius nivosus', 'freebase_id': 'tbd'},
    {'id': 222, 'name': 'Battus philenor', 'freebase_id': 'tbd'},
    {'id': 223, 'name': 'Boisea rubrolineata', 'freebase_id': 'tbd'},
    {'id': 224, 'name': 'Boisea trivittata', 'freebase_id': 'tbd'},
    {'id': 225, 'name': 'Boloria bellona', 'freebase_id': 'tbd'},
    {'id': 226, 'name': 'Bombus bimaculatus', 'freebase_id': 'tbd'},
    {'id': 227, 'name': 'Bombus griseocollis', 'freebase_id': 'tbd'},
    {'id': 228, 'name': 'Bombus impatiens', 'freebase_id': 'tbd'},
    {'id': 229, 'name': 'Bombus pensylvanicus', 'freebase_id': 'tbd'},
    {'id': 230, 'name': 'Bombus sonorus', 'freebase_id': 'tbd'},
    {'id': 231, 'name': 'Bombus ternarius', 'freebase_id': 'tbd'},
    {'id': 232, 'name': 'Bombus terrestris', 'freebase_id': 'tbd'},
    {'id': 233, 'name': 'Bombus vosnesenskii', 'freebase_id': 'tbd'},
    {'id': 234, 'name': 'Bombylius major', 'freebase_id': 'tbd'},
    {'id': 235, 'name': 'Brachymesia gravida', 'freebase_id': 'tbd'},
    {'id': 236, 'name': 'Brechmorhoga mendax', 'freebase_id': 'tbd'},
    {'id': 237, 'name': 'Brephidium exilis', 'freebase_id': 'tbd'},
    {'id': 238, 'name': 'Caenurgina erechtea', 'freebase_id': 'tbd'},
    {'id': 239, 'name': 'Calephelis nemesis', 'freebase_id': 'tbd'},
    {'id': 240, 'name': 'Callophrys augustinus', 'freebase_id': 'tbd'},
    {'id': 241, 'name': 'Callophrys gryneus', 'freebase_id': 'tbd'},
    {'id': 242, 'name': 'Calopteron reticulatum', 'freebase_id': 'tbd'},
    {'id': 243, 'name': 'Calopteryx aequabilis', 'freebase_id': 'tbd'},
    {'id': 244, 'name': 'Calopteryx maculata', 'freebase_id': 'tbd'},
    {'id': 245, 'name': 'Calopteryx splendens', 'freebase_id': 'tbd'},
    {'id': 246, 'name': 'Calopteryx virgo', 'freebase_id': 'tbd'},
    {'id': 247, 'name': 'Calosoma scrutator', 'freebase_id': 'tbd'},
    {'id': 248, 'name': 'Calpodes ethlius', 'freebase_id': 'tbd'},
    {'id': 249, 'name': 'Calycopis cecrops', 'freebase_id': 'tbd'},
    {'id': 250, 'name': 'Calycopis isobeon', 'freebase_id': 'tbd'},
    {'id': 251, 'name': 'Campaea perlata', 'freebase_id': 'tbd'},
    {'id': 252, 'name': 'Celastrina echo', 'freebase_id': 'tbd'},
    {'id': 253, 'name': 'Celastrina neglecta', 'freebase_id': 'tbd'},
    {'id': 254, 'name': 'Celithemis elisa', 'freebase_id': 'tbd'},
    {'id': 255, 'name': 'Celithemis eponina', 'freebase_id': 'tbd'},
    {'id': 256, 'name': 'Ceratomia undulosa', 'freebase_id': 'tbd'},
    {'id': 257, 'name': 'Cercyonis pegala', 'freebase_id': 'tbd'},
    {'id': 258, 'name': 'Chauliognathus marginatus', 'freebase_id': 'tbd'},
    {'id': 259, 'name': 'Chauliognathus pensylvanicus', 'freebase_id': 'tbd'},
    {'id': 260, 'name': 'Chinavia hilaris', 'freebase_id': 'tbd'},
    {'id': 261, 'name': 'Chioides albofasciatus', 'freebase_id': 'tbd'},
    {'id': 262, 'name': 'Chlorochlamys chloroleucaria', 'freebase_id': 'tbd'},
    {'id': 263, 'name': 'Chlosyne ehrenbergii', 'freebase_id': 'tbd'},
    {'id': 264, 'name': 'Chlosyne janais', 'freebase_id': 'tbd'},
    {'id': 265, 'name': 'Chlosyne lacinia', 'freebase_id': 'tbd'},
    {'id': 266, 'name': 'Chlosyne nycteis', 'freebase_id': 'tbd'},
    {'id': 267, 'name': 'Chlosyne palla', 'freebase_id': 'tbd'},
    {'id': 268, 'name': 'Chlosyne theona', 'freebase_id': 'tbd'},
    {'id': 269, 'name': 'Chrysochus auratus', 'freebase_id': 'tbd'},
    {'id': 270, 'name': 'Chrysopilus thoracicus', 'freebase_id': 'tbd'},
    {'id': 271, 'name': 'Cicindela repanda', 'freebase_id': 'tbd'},
    {'id': 272, 'name': 'Cicindela sexguttata', 'freebase_id': 'tbd'},
    {'id': 273, 'name': 'Cisseps fulvicollis', 'freebase_id': 'tbd'},
    {'id': 274, 'name': 'Clepsis peritana', 'freebase_id': 'tbd'},
    {'id': 275, 'name': 'Coccinella californica', 'freebase_id': 'tbd'},
    {'id': 276, 'name': 'Coccinella septempunctata', 'freebase_id': 'tbd'},
    {'id': 277, 'name': 'Coenonympha pamphilus', 'freebase_id': 'tbd'},
    {'id': 278, 'name': 'Coenonympha tullia', 'freebase_id': 'tbd'},
    {'id': 279, 'name': 'Coleomegilla maculata', 'freebase_id': 'tbd'},
    {'id': 280, 'name': 'Colias eurytheme', 'freebase_id': 'tbd'},
    {'id': 281, 'name': 'Colias philodice', 'freebase_id': 'tbd'},
    {'id': 282, 'name': 'Copaeodes minima', 'freebase_id': 'tbd'},
    {'id': 283, 'name': 'Copestylum mexicanum', 'freebase_id': 'tbd'},
    {'id': 284, 'name': 'Corydalus cornutus', 'freebase_id': 'tbd'},
    {'id': 285, 'name': 'Costaconvexa centrostrigaria', 'freebase_id': 'tbd'},
    {'id': 286, 'name': 'Cotinis mutabilis', 'freebase_id': 'tbd'},
    {'id': 287, 'name': 'Cotinis nitida', 'freebase_id': 'tbd'},
    {'id': 288, 'name': 'Crambus agitatellus', 'freebase_id': 'tbd'},
    {'id': 289, 'name': 'Crocothemis erythraea', 'freebase_id': 'tbd'},
    {'id': 290, 'name': 'Crocothemis servilia', 'freebase_id': 'tbd'},
    {'id': 291, 'name': 'Ctenucha virginica', 'freebase_id': 'tbd'},
    {'id': 292, 'name': 'Cupido comyntas', 'freebase_id': 'tbd'},
    {'id': 293, 'name': 'Cycloneda munda', 'freebase_id': 'tbd'},
    {'id': 294, 'name': 'Cycloneda sanguinea', 'freebase_id': 'tbd'},
    {'id': 295, 'name': 'Cydia latiferreana', 'freebase_id': 'tbd'},
    {'id': 296, 'name': 'Danaus eresimus', 'freebase_id': 'tbd'},
    {'id': 297, 'name': 'Danaus gilippus', 'freebase_id': 'tbd'},
    {'id': 298, 'name': 'Danaus plexippus', 'freebase_id': 'tbd'},
    {'id': 299, 'name': 'Darapsa myron', 'freebase_id': 'tbd'},
    {'id': 300, 'name': 'Delphinia picta', 'freebase_id': 'tbd'},
    {'id': 301, 'name': 'Diabrotica undecimpunctata', 'freebase_id': 'tbd'},
    {'id': 302, 'name': 'Dione moneta', 'freebase_id': 'tbd'},
    {'id': 303, 'name': 'Dioprosopa clavata', 'freebase_id': 'tbd'},
    {'id': 304, 'name': 'Dolichovespula maculata', 'freebase_id': 'tbd'},
    {'id': 305, 'name': 'Drepana arcuata', 'freebase_id': 'tbd'},
    {'id': 306, 'name': 'Dromogomphus spinosus', 'freebase_id': 'tbd'},
    {'id': 307, 'name': 'Dromogomphus spoliatus', 'freebase_id': 'tbd'},
    {'id': 308, 'name': 'Dryas iulia', 'freebase_id': 'tbd'},
    {'id': 309, 'name': 'Dryocampa rubicunda', 'freebase_id': 'tbd'},
    {'id': 310, 'name': 'Dythemis fugax', 'freebase_id': 'tbd'},
    {'id': 311, 'name': 'Dythemis nigrescens', 'freebase_id': 'tbd'},
    {'id': 312, 'name': 'Dythemis velox', 'freebase_id': 'tbd'},
    {'id': 313, 'name': 'Ammospermophilus leucurus', 'freebase_id': 'tbd'},
    {'id': 314, 'name': 'Antilocapra americana', 'freebase_id': 'tbd'},
    {'id': 315, 'name': 'Arctocephalus forsteri', 'freebase_id': 'tbd'},
    {'id': 316, 'name': 'Bassariscus astutus', 'freebase_id': 'tbd'},
    {'id': 317, 'name': 'Bison bison', 'freebase_id': 'tbd'},
    {'id': 318, 'name': 'Callospermophilus lateralis', 'freebase_id': 'tbd'},
    {'id': 319, 'name': 'Canis latrans', 'freebase_id': 'tbd'},
    {'id': 320, 'name': 'Capreolus capreolus', 'freebase_id': 'tbd'},
    {'id': 321, 'name': 'Castor canadensis', 'freebase_id': 'tbd'},
    {'id': 322, 'name': 'Cynomys ludovicianus', 'freebase_id': 'tbd'},
    {'id': 323, 'name': 'Dasypus novemcinctus', 'freebase_id': 'tbd'},
    {'id': 324, 'name': 'Didelphis virginiana', 'freebase_id': 'tbd'},
    {'id': 325, 'name': 'Enhydra lutris', 'freebase_id': 'tbd'},
    {'id': 326, 'name': 'Erethizon dorsatum', 'freebase_id': 'tbd'},
    {'id': 327, 'name': 'Erinaceus europaeus', 'freebase_id': 'tbd'},
    {'id': 328, 'name': 'Felis catus', 'freebase_id': 'tbd'},
    {'id': 329, 'name': 'Lepus americanus', 'freebase_id': 'tbd'},
    {'id': 330, 'name': 'Lepus californicus', 'freebase_id': 'tbd'},
    {'id': 331, 'name': 'Lepus europaeus', 'freebase_id': 'tbd'},
    {'id': 332, 'name': 'Lontra canadensis', 'freebase_id': 'tbd'},
    {'id': 333, 'name': 'Loxodonta africana', 'freebase_id': 'tbd'},
    {'id': 334, 'name': 'Lynx rufus', 'freebase_id': 'tbd'},
    {'id': 335, 'name': 'Marmota flaviventris', 'freebase_id': 'tbd'},
    {'id': 336, 'name': 'Marmota monax', 'freebase_id': 'tbd'},
    {'id': 337, 'name': 'Megaptera novaeangliae', 'freebase_id': 'tbd'},
    {'id': 338, 'name': 'Mephitis mephitis', 'freebase_id': 'tbd'},
    {'id': 339, 'name': 'Mirounga angustirostris', 'freebase_id': 'tbd'},
    {'id': 340, 'name': 'Myocastor coypus', 'freebase_id': 'tbd'},
    {'id': 341, 'name': 'Nasua narica', 'freebase_id': 'tbd'},
    {'id': 342, 'name': 'Neovison vison', 'freebase_id': 'tbd'},
    {'id': 343, 'name': 'Ochotona princeps', 'freebase_id': 'tbd'},
    {'id': 344, 'name': 'Odocoileus hemionus', 'freebase_id': 'tbd'},
    {'id': 345, 'name': 'Odocoileus virginianus', 'freebase_id': 'tbd'},
    {'id': 346, 'name': 'Ondatra zibethicus', 'freebase_id': 'tbd'},
    {'id': 347, 'name': 'Oryctolagus cuniculus', 'freebase_id': 'tbd'},
    {'id': 348, 'name': 'Otospermophilus beecheyi', 'freebase_id': 'tbd'},
    {'id': 349, 'name': 'Otospermophilus variegatus', 'freebase_id': 'tbd'},
    {'id': 350, 'name': 'Ovis canadensis', 'freebase_id': 'tbd'},
    {'id': 351, 'name': 'Panthera leo', 'freebase_id': 'tbd'},
    {'id': 352, 'name': 'Pecari tajacu', 'freebase_id': 'tbd'},
    {'id': 353, 'name': 'Phoca vitulina', 'freebase_id': 'tbd'},
    {'id': 354, 'name': 'Procyon lotor', 'freebase_id': 'tbd'},
    {'id': 355, 'name': 'Sciurus aureogaster', 'freebase_id': 'tbd'},
    {'id': 356, 'name': 'Sciurus carolinensis', 'freebase_id': 'tbd'},
    {'id': 357, 'name': 'Sciurus griseus', 'freebase_id': 'tbd'},
    {'id': 358, 'name': 'Sciurus niger', 'freebase_id': 'tbd'},
    {'id': 359, 'name': 'Sciurus vulgaris', 'freebase_id': 'tbd'},
    {'id': 360, 'name': 'Sus scrofa', 'freebase_id': 'tbd'},
    {'id': 361, 'name': 'Sylvilagus audubonii', 'freebase_id': 'tbd'},
    {'id': 362, 'name': 'Sylvilagus bachmani', 'freebase_id': 'tbd'},
    {'id': 363, 'name': 'Sylvilagus floridanus', 'freebase_id': 'tbd'},
    {'id': 364, 'name': 'Tamias striatus', 'freebase_id': 'tbd'},
    {'id': 365, 'name': 'Tamiasciurus douglasii', 'freebase_id': 'tbd'},
    {'id': 366, 'name': 'Tamiasciurus hudsonicus', 'freebase_id': 'tbd'},
    {'id': 367, 'name': 'Thomomys bottae', 'freebase_id': 'tbd'},
    {'id': 368, 'name': 'Tursiops truncatus', 'freebase_id': 'tbd'},
    {'id': 369, 'name': 'Urocyon cinereoargenteus', 'freebase_id': 'tbd'},
    {'id': 370, 'name': 'Ursus americanus', 'freebase_id': 'tbd'},
    {'id': 371, 'name': 'Vulpes vulpes', 'freebase_id': 'tbd'},
    {'id': 372, 'name': 'Zalophus californianus', 'freebase_id': 'tbd'},
    {'id': 373, 'name': 'Acanthodoris lutea', 'freebase_id': 'tbd'},
    {'id': 374, 'name': 'Aplysia californica', 'freebase_id': 'tbd'},
    {'id': 375, 'name': 'Ariolimax columbianus', 'freebase_id': 'tbd'},
    {'id': 376, 'name': 'Calliostoma ligatum', 'freebase_id': 'tbd'},
    {'id': 377, 'name': 'Cepaea nemoralis', 'freebase_id': 'tbd'},
    {'id': 378, 'name': 'Corbicula fluminea', 'freebase_id': 'tbd'},
    {'id': 379, 'name': 'Cornu aspersum', 'freebase_id': 'tbd'},
    {'id': 380, 'name': 'Cryptochiton stelleri', 'freebase_id': 'tbd'},
    {'id': 381, 'name': 'Deroceras reticulatum', 'freebase_id': 'tbd'},
    {'id': 382, 'name': 'Doris montereyensis', 'freebase_id': 'tbd'},
    {'id': 383, 'name': 'Geitodoris heathi', 'freebase_id': 'tbd'},
    {'id': 384, 'name': 'Hermissenda opalescens', 'freebase_id': 'tbd'},
    {'id': 385, 'name': 'Leukoma staminea', 'freebase_id': 'tbd'},
    {'id': 386, 'name': 'Limax maximus', 'freebase_id': 'tbd'},
    {'id': 387, 'name': 'Okenia rosacea', 'freebase_id': 'tbd'},
    {'id': 388, 'name': 'Otala lactea', 'freebase_id': 'tbd'},
    {'id': 389, 'name': 'Peltodoris nobilis', 'freebase_id': 'tbd'},
    {'id': 390, 'name': 'Phidiana hiltoni', 'freebase_id': 'tbd'},
    {'id': 391, 'name': 'Rumina decollata', 'freebase_id': 'tbd'},
    {'id': 392, 'name': 'Triopha catalinae', 'freebase_id': 'tbd'},
    {'id': 393, 'name': 'Triopha maculata', 'freebase_id': 'tbd'},
    {'id': 394, 'name': 'Actinemys marmorata', 'freebase_id': 'tbd'},
    {'id': 395, 'name': 'Alligator mississippiensis', 'freebase_id': 'tbd'},
    {'id': 396, 'name': 'Anguis fragilis', 'freebase_id': 'tbd'},
    {'id': 397, 'name': 'Anolis carolinensis', 'freebase_id': 'tbd'},
    {'id': 398, 'name': 'Anolis nebulosus', 'freebase_id': 'tbd'},
    {'id': 399, 'name': 'Anolis sagrei', 'freebase_id': 'tbd'},
    {'id': 400, 'name': 'Apalone spinifera', 'freebase_id': 'tbd'},
    {'id': 401, 'name': 'Arizona elegans', 'freebase_id': 'tbd'},
    {'id': 402, 'name': 'Aspidoscelis exsanguis', 'freebase_id': 'tbd'},
    {'id': 403, 'name': 'Aspidoscelis gularis', 'freebase_id': 'tbd'},
    {'id': 404, 'name': 'Aspidoscelis tigris', 'freebase_id': 'tbd'},
    {'id': 405, 'name': 'Basiliscus vittatus', 'freebase_id': 'tbd'},
    {'id': 406, 'name': 'Callisaurus draconoides', 'freebase_id': 'tbd'},
    {'id': 407, 'name': 'Calotes versicolor', 'freebase_id': 'tbd'},
    {'id': 408, 'name': 'Charina bottae', 'freebase_id': 'tbd'},
    {'id': 409, 'name': 'Chelonia mydas', 'freebase_id': 'tbd'},
    {'id': 410, 'name': 'Chelydra serpentina', 'freebase_id': 'tbd'},
    {'id': 411, 'name': 'Chrysemys picta', 'freebase_id': 'tbd'},
    {'id': 412, 'name': 'Coleonyx variegatus', 'freebase_id': 'tbd'},
    {'id': 413, 'name': 'Coluber constrictor', 'freebase_id': 'tbd'},
    {'id': 414, 'name': 'Cophosaurus texanus', 'freebase_id': 'tbd'},
    {'id': 415, 'name': 'Crocodylus acutus', 'freebase_id': 'tbd'},
    {'id': 416, 'name': 'Crotalus atrox', 'freebase_id': 'tbd'},
    {'id': 417, 'name': 'Crotalus horridus', 'freebase_id': 'tbd'},
    {'id': 418, 'name': 'Crotalus oreganus', 'freebase_id': 'tbd'},
    {'id': 419, 'name': 'Crotalus ruber', 'freebase_id': 'tbd'},
    {'id': 420, 'name': 'Crotalus scutulatus', 'freebase_id': 'tbd'},
    {'id': 421, 'name': 'Crotalus viridis', 'freebase_id': 'tbd'},
    {'id': 422, 'name': 'Crotaphytus bicinctores', 'freebase_id': 'tbd'},
    {'id': 423, 'name': 'Crotaphytus collaris', 'freebase_id': 'tbd'},
    {'id': 424, 'name': 'Ctenosaura pectinata', 'freebase_id': 'tbd'},
    {'id': 425, 'name': 'Ctenosaura similis', 'freebase_id': 'tbd'},
    {'id': 426, 'name': 'Diadophis punctatus', 'freebase_id': 'tbd'},
    {'id': 427, 'name': 'Dipsosaurus dorsalis', 'freebase_id': 'tbd'},
    {'id': 428, 'name': 'Elgaria coerulea', 'freebase_id': 'tbd'},
    {'id': 429, 'name': 'Elgaria multicarinata', 'freebase_id': 'tbd'},
    {'id': 430, 'name': 'Eretmochelys imbricata', 'freebase_id': 'tbd'},
    {'id': 431, 'name': 'Gopherus agassizii', 'freebase_id': 'tbd'},
    {'id': 432, 'name': 'Gopherus berlandieri', 'freebase_id': 'tbd'},
    {'id': 433, 'name': 'Gopherus polyphemus', 'freebase_id': 'tbd'},
    {'id': 434, 'name': 'Heloderma suspectum', 'freebase_id': 'tbd'},
    {'id': 435, 'name': 'Hemidactylus frenatus', 'freebase_id': 'tbd'},
    {'id': 436, 'name': 'Hemidactylus turcicus', 'freebase_id': 'tbd'},
    {'id': 437, 'name': 'Heterodon platirhinos', 'freebase_id': 'tbd'},
    {'id': 438, 'name': 'Hypsiglena jani', 'freebase_id': 'tbd'},
    {'id': 439, 'name': 'Iguana iguana', 'freebase_id': 'tbd'},
    {'id': 440, 'name': 'Kinosternon flavescens', 'freebase_id': 'tbd'},
    {'id': 441, 'name': 'Lampropeltis californiae', 'freebase_id': 'tbd'},
    {'id': 442, 'name': 'Lampropeltis holbrooki', 'freebase_id': 'tbd'},
    {'id': 443, 'name': 'Micrurus tener', 'freebase_id': 'tbd'},
    {'id': 444, 'name': 'Nerodia erythrogaster', 'freebase_id': 'tbd'},
    {'id': 445, 'name': 'Nerodia rhombifer', 'freebase_id': 'tbd'},
    {'id': 446, 'name': 'Nerodia sipedon', 'freebase_id': 'tbd'},
    {'id': 447, 'name': 'Opheodrys aestivus', 'freebase_id': 'tbd'},
    {'id': 448, 'name': 'Pantherophis alleghaniensis', 'freebase_id': 'tbd'},
    {'id': 449, 'name': 'Pantherophis emoryi', 'freebase_id': 'tbd'},
    {'id': 450, 'name': 'Pantherophis obsoletus', 'freebase_id': 'tbd'},
    {'id': 451, 'name': 'Pantherophis spiloides', 'freebase_id': 'tbd'},
    {'id': 452, 'name': 'Phelsuma laticauda', 'freebase_id': 'tbd'},
    {'id': 453, 'name': 'Phrynosoma blainvillii', 'freebase_id': 'tbd'},
    {'id': 454, 'name': 'Phrynosoma cornutum', 'freebase_id': 'tbd'},
    {'id': 455, 'name': 'Phrynosoma hernandesi', 'freebase_id': 'tbd'},
    {'id': 456, 'name': 'Phrynosoma modestum', 'freebase_id': 'tbd'},
    {'id': 457, 'name': 'Phrynosoma platyrhinos', 'freebase_id': 'tbd'},
    {'id': 458, 'name': 'Pituophis catenifer', 'freebase_id': 'tbd'},
    {'id': 459, 'name': 'Plestiodon fasciatus', 'freebase_id': 'tbd'},
    {'id': 460, 'name': 'Plestiodon laticeps', 'freebase_id': 'tbd'},
    {'id': 461, 'name': 'Plestiodon obsoletus', 'freebase_id': 'tbd'},
    {'id': 462, 'name': 'Plestiodon skiltonianus', 'freebase_id': 'tbd'},
    {'id': 463, 'name': 'Podarcis muralis', 'freebase_id': 'tbd'},
    {'id': 464, 'name': 'Pseudemys texana', 'freebase_id': 'tbd'},
    {'id': 465, 'name': 'Rena dulcis', 'freebase_id': 'tbd'},
    {'id': 466, 'name': 'Rhinocheilus lecontei', 'freebase_id': 'tbd'},
    {'id': 467, 'name': 'Sauromalus ater', 'freebase_id': 'tbd'},
    {'id': 468, 'name': 'Sceloporus consobrinus', 'freebase_id': 'tbd'},
    {'id': 469, 'name': 'Sceloporus cowlesi', 'freebase_id': 'tbd'},
    {'id': 470, 'name': 'Sceloporus graciosus', 'freebase_id': 'tbd'},
    {'id': 471, 'name': 'Sceloporus magister', 'freebase_id': 'tbd'},
    {'id': 472, 'name': 'Sceloporus occidentalis', 'freebase_id': 'tbd'},
    {'id': 473, 'name': 'Sceloporus olivaceus', 'freebase_id': 'tbd'},
    {'id': 474, 'name': 'Sceloporus orcutti', 'freebase_id': 'tbd'},
    {'id': 475, 'name': 'Sceloporus poinsettii', 'freebase_id': 'tbd'},
    {'id': 476, 'name': 'Sceloporus torquatus', 'freebase_id': 'tbd'},
    {'id': 477, 'name': 'Sceloporus tristichus', 'freebase_id': 'tbd'},
    {'id': 478, 'name': 'Sceloporus undulatus', 'freebase_id': 'tbd'},
    {'id': 479, 'name': 'Sceloporus uniformis', 'freebase_id': 'tbd'},
    {'id': 480, 'name': 'Sceloporus variabilis', 'freebase_id': 'tbd'},
    {'id': 481, 'name': 'Scincella lateralis', 'freebase_id': 'tbd'},
    {'id': 482, 'name': 'Sonora semiannulata', 'freebase_id': 'tbd'},
    {'id': 483, 'name': 'Sphenodon punctatus', 'freebase_id': 'tbd'},
    {'id': 484, 'name': 'Sternotherus odoratus', 'freebase_id': 'tbd'},
    {'id': 485, 'name': 'Storeria dekayi', 'freebase_id': 'tbd'},
    {'id': 486, 'name': 'Storeria occipitomaculata', 'freebase_id': 'tbd'},
    {'id': 487, 'name': 'Tantilla gracilis', 'freebase_id': 'tbd'},
    {'id': 488, 'name': 'Tarentola mauritanica', 'freebase_id': 'tbd'},
    {'id': 489, 'name': 'Terrapene carolina', 'freebase_id': 'tbd'},
    {'id': 490, 'name': 'Terrapene ornata', 'freebase_id': 'tbd'},
    {'id': 491, 'name': 'Thamnophis cyrtopsis', 'freebase_id': 'tbd'},
    {'id': 492, 'name': 'Thamnophis elegans', 'freebase_id': 'tbd'},
    {'id': 493, 'name': 'Thamnophis hammondii', 'freebase_id': 'tbd'},
    {'id': 494, 'name': 'Thamnophis marcianus', 'freebase_id': 'tbd'},
    {'id': 495, 'name': 'Thamnophis proximus', 'freebase_id': 'tbd'},
    {'id': 496, 'name': 'Thamnophis sirtalis', 'freebase_id': 'tbd'},
    {'id': 497, 'name': 'Trachemys scripta', 'freebase_id': 'tbd'},
    {'id': 498, 'name': 'Urosaurus ornatus', 'freebase_id': 'tbd'},
    {'id': 499, 'name': 'Uta stansburiana', 'freebase_id': 'tbd'},
    {'id': 500, 'name': 'Zootoca vivipara', 'freebase_id': 'tbd'}
]

PER_LAYER_CATEGORY_NAMES = {
    'l1': categories_l1,
    'l2': categories_l2,
    'l3': categories_l3,
    'l4': categories_l4,
    'l5': categories_l5,
    'l6': categories,
}